server:
  port: 4004

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: auth-service-route
              uri: http://auth-service:4005
              predicates:
                - Path=/api-gateway/auth/**
              filters:
                - StripPrefix=2

            ## REST Client --> http://localhost:4004/api-gateway/patients
            ## API Gateway --> http://patient-service:4000/patients
            - id: patient-service-route
              uri: http://patient-service:4000
              predicates:
                - Path=/api-gateway/patient/**
              filters:
                - StripPrefix=1

            ## REST Client --> http://localhost:4004/api-docs/patients
            ## API Gateway --> http://patient-service:4000/v3/api-docs
            - id: patient-service-api-docs-route
              uri: http://patient-service:4000
              predicates:
                - Path=/api-docs/patient
              filters:
                - RewritePath=/api-docs/patient,/v3/api-docs


            - id: patient-service-swagger-ui
              uri: http://patient-service:4000
              predicates:
                - Path=/swagger-ui.html
