### POST request to create a patient
POST http://localhost:4004/api-gateway/patient
Content-Type: application/json

{
  "name": "Dilrangi Sankalpana",
  "email": "sankalpana00@gmail.com",
  "address": "Meegahasewana, Unella, Palatuwa",
  "dateOfBirth": "2000-05-18"
}

###